version: '3.1'

services:
    ubuntu:
        build: .
        # image: ubuntu
        environment:
            MYNAME: "naoki"
        command: ls -Falt
        tty: true
        stdin_open: true

    # vim:
    #     image: vim:latest


# volumes: 

